#pragma once

#define GUEST_RUNTIME_STUBS(X)                                                                               \
	X(rv32_ill)                                                                                          \
	X(rv32_fence)                                                                                        \
	X(rv32_fencei)                                                                                       \
	X(rv32_ecall)                                                                                        \
	X(rv32_ebreak)                                                                                       \
	X(rv32_lrw)                                                                                          \
	X(rv32_scw)                                                                                          \
	X(rv32_amoswapw)                                                                                     \
	X(rv32_amoaddw)                                                                                      \
	X(rv32_amoxorw)                                                                                      \
	X(rv32_amoandw)                                                                                      \
	X(rv32_amoorw)                                                                                       \
	X(rv32_amominw)                                                                                      \
	X(rv32_amomaxw)                                                                                      \
	X(rv32_amominuw)                                                                                     \
	X(rv32_amomaxuw)                                                                                     \
	X(rv32_mul)                                                                                          \
	X(rv32_mulh)                                                                                         \
	X(rv32_mulhsu)                                                                                       \
	X(rv32_mulhu)                                                                                        \
	X(rv32_div)                                                                                          \
	X(rv32_divu)                                                                                         \
	X(rv32_rem)                                                                                          \
	X(rv32_remu)                                                                                         \
	X(rv32_csrrw)                                                                                        \
	X(rv32_csrrs)                                                                                        \
	X(rv32_csrrc)                                                                                        \
	X(rv32_csrrwi)                                                                                       \
	X(rv32_csrrsi)                                                                                       \
	X(rv32_csrrci)                                                                                       \
	X(rv32_mret)                                                                                         \
